ALTER TABLE categories ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE email_filters ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE templates ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE parameter_sets ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE automations ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
