#!/usr/bin/env bash
# Postwerk deploy — runs ON the VM (invoked by GitHub Actions over an IAP SSH
# tunnel, or manually). Pulls PRE-BUILT images from Artifact Registry (built
# ONCE in CI), regenerates .env from Secret Manager, brings the stack up,
# health-checks, and auto-rolls-back to the last-good image on failure.
# The VM never builds images.
#
# Usage:  IMAGE_TAG=sha-<git-sha> ./deploy/deploy.sh   (CI passes IMAGE_TAG)
#         ./deploy/deploy.sh                           (manual → defaults to :latest)
#
# Prereqs on the VM: docker, docker compose, gcloud CLI, and the VM service
# account with roles/secretmanager.secretAccessor + roles/artifactregistry.reader
# (both provisioned by Terraform).
set -euo pipefail

PROJECT="postwerk"
REGION="europe-west3"
COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env"
IMAGE_TAG="${IMAGE_TAG:-latest}"
STATE_FILE="${HOME}/.postwerk_last_good_tag"
HEALTH_RETRIES=30
HEALTH_INTERVAL=10

# Always run from the repo root (this script lives in ./deploy).
cd "$(dirname "$0")/.."

echo "==> Deploying tag: ${IMAGE_TAG}"

# Let docker pull from Artifact Registry using the VM's service account creds.
gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet >/dev/null 2>&1 || true

echo "==> Fetching secrets from Secret Manager…"
sec() { gcloud secrets versions access latest --secret="$1" --project="$PROJECT"; }

# Generate .env fresh. Non-secret config is inline; secrets come from Secret Manager.
umask 077
cat > "$ENV_FILE" <<EOF
# AUTO-GENERATED by deploy/deploy.sh — DO NOT edit by hand, DO NOT commit.
IMAGE_TAG=${IMAGE_TAG}
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=postwerk
POSTGRES_USER=postwerk
REDIS_HOST=redis
REDIS_PORT=6379
SPRING_PROFILES_ACTIVE=prod
SERVER_PORT=8080
FRONTEND_PORT=80
APP_PUBLIC_BASE_URL=https://postwerk.io
APP_FRONTEND_BASE_URL=https://postwerk.io
CORS_ALLOWED_ORIGINS=https://postwerk.io,https://www.postwerk.io
GEMINI_CHAT_MODEL=gemini-2.5-pro
# Transactional email via Resend SMTP (Zoho keeps RECEIVING via MX; Resend only SENDS).
MAIL_ENABLED=true
MAIL_HOST=smtp.resend.com
MAIL_PORT=587
MAIL_USERNAME=resend
MAIL_FROM=noreply@postwerk.io
MAIL_FROM_NAME=Postwerk
POSTGRES_PASSWORD=$(sec postwerk-postgres-password)
REDIS_PASSWORD=$(sec postwerk-redis-password)
JWT_SECRET=$(sec postwerk-jwt-secret)
ENCRYPTION_KEY=$(sec postwerk-encryption-key)
GEMINI_API_KEY=$(sec postwerk-gemini-api-key)
MAIL_PASSWORD=$(sec postwerk-mail-password)
EOF
chmod 600 "$ENV_FILE"
echo "    .env generated ($(wc -l < "$ENV_FILE") lines)."

compose() { docker compose -f "$COMPOSE_FILE" "$@"; }

bring_up() {
  local tag="$1"
  echo "==> Pulling images (tag ${tag})…"
  IMAGE_TAG="$tag" compose pull
  echo "==> Starting stack…"
  IMAGE_TAG="$tag" compose up -d --remove-orphans
}

health_ok() {
  echo "==> Waiting for backend health (max $((HEALTH_RETRIES * HEALTH_INTERVAL))s)…"
  local i
  for i in $(seq 1 "$HEALTH_RETRIES"); do
    if compose exec -T backend curl -fsS http://127.0.0.1:8080/api/v1/health >/dev/null 2>&1; then
      echo "    backend healthy after ~$((i * HEALTH_INTERVAL))s."
      return 0
    fi
    sleep "$HEALTH_INTERVAL"
  done
  return 1
}

# Remember the last tag that passed health so we can roll back to it.
PREV_TAG="$(cat "$STATE_FILE" 2>/dev/null || echo '')"

bring_up "$IMAGE_TAG"

if health_ok; then
  echo "$IMAGE_TAG" > "$STATE_FILE"
  echo "==> Deploy OK: ${IMAGE_TAG}  →  https://postwerk.io"
else
  echo "!!  Health check FAILED for ${IMAGE_TAG}"
  if [ -n "$PREV_TAG" ] && [ "$PREV_TAG" != "$IMAGE_TAG" ]; then
    echo "==> Rolling back to last-good tag: ${PREV_TAG}"
    sed -i "s|^IMAGE_TAG=.*|IMAGE_TAG=${PREV_TAG}|" "$ENV_FILE"
    bring_up "$PREV_TAG"
    if health_ok; then
      echo "==> Rolled back to ${PREV_TAG}. Investigate the failed deploy."
    else
      echo "!!  Rollback to ${PREV_TAG} ALSO failed — manual intervention needed."
    fi
  else
    echo "!!  No previous good tag recorded; cannot auto-roll-back."
  fi
  exit 1
fi
