#!/usr/bin/env bash
# Postwerk deploy script — runs ON the VM.
# 1. Pulls latest code  2. Generates .env from Secret Manager  3. Brings stack up.
#
# Prereqs on the VM: docker, docker compose, gcloud CLI, and the VM's service
# account must have roles/secretmanager.secretAccessor (provisioned by Terraform).
set -euo pipefail

PROJECT="postwerk"
COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env"

# Always run from the repo root (this script lives in ./deploy).
cd "$(dirname "$0")/.."

echo "==> Pulling latest code (branch main)…"
git pull --ff-only origin main

echo "==> Fetching secrets from Secret Manager…"
sec() { gcloud secrets versions access latest --secret="$1" --project="$PROJECT"; }

# Generate .env fresh. Non-secret config is inline; secrets come from Secret Manager.
umask 077
cat > "$ENV_FILE" <<EOF
# AUTO-GENERATED by deploy/deploy.sh — DO NOT edit by hand, DO NOT commit.
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=postwerk
POSTGRES_USER=postwerk
REDIS_HOST=redis
REDIS_PORT=6379
SPRING_PROFILES_ACTIVE=prod
SERVER_PORT=8080
FRONTEND_PORT=80
APP_PUBLIC_BASE_URL=https://postwerk.io
APP_FRONTEND_BASE_URL=https://postwerk.io
CORS_ALLOWED_ORIGINS=https://postwerk.io,https://www.postwerk.io
GEMINI_CHAT_MODEL=gemini-2.5-pro
# Transactional email via Resend SMTP (Zoho keeps RECEIVING via MX; Resend only SENDS).
MAIL_ENABLED=true
MAIL_HOST=smtp.resend.com
MAIL_PORT=587
MAIL_USERNAME=resend
MAIL_FROM=noreply@postwerk.io
MAIL_FROM_NAME=Postwerk
POSTGRES_PASSWORD=$(sec postwerk-postgres-password)
REDIS_PASSWORD=$(sec postwerk-redis-password)
JWT_SECRET=$(sec postwerk-jwt-secret)
ENCRYPTION_KEY=$(sec postwerk-encryption-key)
GEMINI_API_KEY=$(sec postwerk-gemini-api-key)
MAIL_PASSWORD=$(sec postwerk-mail-password)
EOF
chmod 600 "$ENV_FILE"
echo "    .env generated ($(wc -l < "$ENV_FILE") lines)."

echo "==> Building & starting the stack…"
docker compose -f "$COMPOSE_FILE" up -d --build

echo "==> Done. Check: https://postwerk.io  (logs: docker compose -f $COMPOSE_FILE logs -f)"
